/**
 * Allowed task status values.
 *
 * @type {readonly string[]}
 */
export const TASK_STATUSES = Object.freeze(['todo', 'in-progress', 'done']);

/**
 * Allowed task priority values.
 *
 * @type {readonly string[]}
 */
export const TASK_PRIORITIES = Object.freeze(['low', 'medium', 'high']);

/**
 * Priority weight map for sorting.
 *
 * @type {Readonly<Record<string, number>>}
 */
export const PRIORITY_RANK = Object.freeze({
  low: 1,
  medium: 2,
  high: 3
});

/**
 * Default category used when none is provided.
 *
 * @type {string}
 */
export const DEFAULT_TASK_CATEGORY = 'general';

/**
 * Validate and normalize a task title.
 *
 * @param {string} title - User-provided task title.
 * @returns {string} Trimmed title.
 * @throws {TypeError} If the title is not a valid non-empty string.
 * @example
 * validateTitle('Buy milk');
 * @example
 * validateTitle('  Prepare sprint plan  ');
 */
export function validateTitle(title) {
  if (typeof title !== 'string') {
    throw new TypeError('Invalid input: title must be a string.');
  }

  const normalizedTitle = title.trim();
  if (normalizedTitle.length === 0 || normalizedTitle.length > 120) {
    throw new TypeError('Invalid input: title length must be between 1 and 120 characters.');
  }

  return normalizedTitle;
}

/**
 * Validate and normalize a task description.
 *
 * @param {string} description - User-provided description.
 * @returns {string} Trimmed description.
 * @throws {TypeError} If the description is not a valid string.
 * @example
 * validateDescription('Call vendor about contract renewal');
 * @example
 * validateDescription('');
 */
export function validateDescription(description) {
  if (typeof description !== 'string') {
    throw new TypeError('Invalid input: description must be a string.');
  }

  const normalizedDescription = description.trim();
  if (normalizedDescription.length > 1000) {
    throw new TypeError('Invalid input: description must be 1000 characters or fewer.');
  }

  return normalizedDescription;
}

/**
 * Validate a task status enum value.
 *
 * @param {string} status - Status value.
 * @returns {'todo' | 'in-progress' | 'done'} Validated status.
 * @throws {TypeError} If the status is not one of the allowed values.
 * @example
 * validateStatus('todo');
 * @example
 * validateStatus('in-progress');
 */
export function validateStatus(status) {
  if (typeof status !== 'string' || !TASK_STATUSES.includes(status)) {
    throw new TypeError("Invalid input: status must be one of 'todo', 'in-progress', or 'done'.");
  }

  return /** @type {'todo' | 'in-progress' | 'done'} */ (status);
}

/**
 * Validate a task priority enum value.
 *
 * @param {string} priority - Priority value.
 * @returns {'low' | 'medium' | 'high'} Validated priority.
 * @throws {TypeError} If the priority is not one of the allowed values.
 * @example
 * validatePriority('low');
 * @example
 * validatePriority('high');
 */
export function validatePriority(priority) {
  if (typeof priority !== 'string' || !TASK_PRIORITIES.includes(priority)) {
    throw new TypeError("Invalid input: priority must be one of 'low', 'medium', or 'high'.");
  }

  return /** @type {'low' | 'medium' | 'high'} */ (priority);
}

/**
 * Validate and normalize a task category.
 *
 * @param {string} category - Category value.
 * @returns {string} Trimmed category.
 * @throws {TypeError} If category is not a non-empty string.
 * @example
 * validateCategory('work');
 * @example
 * validateCategory('  personal  ');
 */
export function validateCategory(category) {
  if (typeof category !== 'string') {
    throw new TypeError('Invalid input: category must be a string.');
  }

  const normalizedCategory = category.trim();
  if (normalizedCategory.length === 0) {
    throw new TypeError('Invalid input: category must be a non-empty string.');
  }

  return normalizedCategory;
}

/**
 * Validate a task id generated by crypto.randomUUID().
 *
 * @param {string} id - Task id.
 * @returns {string} The validated id.
 * @throws {TypeError} If the id is not a UUID string.
 * @example
 * validateTaskId('550e8400-e29b-41d4-a716-446655440000');
 * @example
 * validateTaskId('6f1f7d59-9c3b-4df0-8cab-5fa3ebea13d6');
 */
export function validateTaskId(id) {
  if (typeof id !== 'string') {
    throw new TypeError('Invalid input: task id must be a string.');
  }

  const uuidPattern =
    /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
  if (!uuidPattern.test(id)) {
    throw new TypeError('Invalid input: task id must be a valid UUID.');
  }

  return id;
}

/**
 * Validate list filters for status and priority.
 *
 * @param {{status?: string, priority?: string, category?: string}} filters - Optional list filters.
 * @returns {{status?: 'todo' | 'in-progress' | 'done', priority?: 'low' | 'medium' | 'high', category?: string}}
 * Validated filters.
 * @throws {TypeError} If filters are not a plain object or contain invalid values.
 * @example
 * validateFilterOptions({ status: 'todo' });
 * @example
 * validateFilterOptions({ priority: 'high' });
 */
export function validateFilterOptions(filters) {
  if (filters === null || typeof filters !== 'object' || Array.isArray(filters)) {
    throw new TypeError('Invalid input: filters must be an object.');
  }

  const validatedFilters = {};

  if (filters.status !== undefined) {
    validatedFilters.status = validateStatus(filters.status);
  }

  if (filters.priority !== undefined) {
    validatedFilters.priority = validatePriority(filters.priority);
  }

  if (filters.category !== undefined) {
    validatedFilters.category = validateCategory(filters.category);
  }

  return validatedFilters;
}

/**
 * Validate list sorting options.
 *
 * @param {{sortBy?: string, sortOrder?: string}} sortOptions - Optional sorting options.
 * @returns {{sortBy: 'priority' | 'createdAt', sortOrder: 'asc' | 'desc'}} Validated sorting options.
 * @throws {TypeError} If sort options are not a plain object or contain invalid values.
 * @example
 * validateSortOptions({ sortBy: 'priority', sortOrder: 'desc' });
 * @example
 * validateSortOptions({ sortBy: 'createdAt' });
 */
export function validateSortOptions(sortOptions) {
  if (sortOptions === null || typeof sortOptions !== 'object' || Array.isArray(sortOptions)) {
    throw new TypeError('Invalid input: sort options must be an object.');
  }

  const sortBy = sortOptions.sortBy ?? 'createdAt';
  const sortOrder = sortOptions.sortOrder ?? 'asc';

  if (sortBy !== 'priority' && sortBy !== 'createdAt') {
    throw new TypeError("Invalid input: sortBy must be either 'priority' or 'createdAt'.");
  }

  if (sortOrder !== 'asc' && sortOrder !== 'desc') {
    throw new TypeError("Invalid input: sortOrder must be either 'asc' or 'desc'.");
  }

  return {
    sortBy,
    sortOrder
  };
}
